-- Grant necessary permissions to ***REMOVED***
GRANT CREATE ON SCHEMA public TO ***REMOVED***;
GRANT ALL ON ALL TABLES IN SCHEMA public TO ***REMOVED***;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO ***REMOVED***;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO ***REMOVED***;